---
title: "Untitled"
output: html_document
date: "2025-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read Excel

```{r setup}
library(readxl)
library(knitr)
library(FactoMineR)
library(factoextra)
library(corrplot)
library(gridExtra)

data = read_excel("data_clean1.xlsx")

descFotocasa = data.frame("variable" = colnames(data),
"tipo" = c ("text","num","num",rep("cat",4),   "date",rep("cat",2),rep("num",7),
rep("bool",4),rep("num",12),"bool"))

```

```{r}
# AFC SIMPLE : neighborhood vs price
hist(data$priceAmount, breaks = 30, col = "lightblue", main = "Distribución de priceAmount", xlab = "priceAmount")

data$priceCategory <- cut(data$priceAmount,
                          breaks = quantile(data$priceAmount, probs = seq(0, 1, length.out = 7), na.rm = TRUE),
                          include.lowest = TRUE,
                          labels = c("Muy Bajo", "Bajo", "Medio Bajo", "Medio Alto", "Alto", "Muy Alto"))

barplot(table(data$priceCategory), col = "lightgreen", main = "Distribución de priceAmount por Categorías")

quantile(data$priceAmount, probs = seq(0, 1, length.out = 7), na.rm = TRUE)

contingency_table <- table(data$municipality, data$priceCategory)

contingency_table
chisq.test(contingency_table, simulate.p.value = TRUE)

## La asociación entre el vecindario (neighborhood) y la categoría de precio (priceCategory) es estadísticamente significativa con un p-valor de 0.0005. Esto sugiere que el precio está relacionado con el vecindario.

```


## Número de dimensiones y obtención del modelo


```{r pressure, echo=FALSE}

res.afc = CA(contingency_table, graph = FALSE)
eig.val <- get_eigenvalue(res.afc)
Vmedia = 100 * (1/nrow(eig.val))
fviz_eig(res.afc, addlabels = TRUE) +
  geom_hline(yintercept=Vmedia, linetype=2, color="red")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r}
res.afc = CA(contingency_table, graph = FALSE, ncp=2)

fviz_ca_row(res.afc, axes = c(1,2), repel = TRUE, col.row = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
```
```{r}
fviz_ca_col(res.afc, axes = c(1,2), repel = TRUE, col.col = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
```

